spring.application.name=agendamento

# Perfil padrao = H2 (dev). Para Oracle: --spring.profiles.active=oracle
spring.profiles.active=h2

# JPA / Hibernate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Sao_Paulo

# Springdoc / Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
