# Banco H2 em memoria (perfil dev)
spring.datasource.url=jdbc:h2:mem:agendamento;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console em http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate

# Flyway aponta para migrations comuns + especificas do H2
spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/h2
