-- Oracle 21c rejeita BIGINT em coluna IDENTITY (ORA-30675), por isso NUMBER(19,0).
CREATE TABLE paciente (
    id              NUMBER(19,0)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR2(150)   NOT NULL,
    cpf             VARCHAR2(14)    NOT NULL,
    email           VARCHAR2(150),
    telefone        VARCHAR2(20),
    data_nascimento DATE,
    criado_em       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_paciente_cpf UNIQUE (cpf)
);

CREATE TABLE profissional (
    id                 NUMBER(19,0)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR2(150)  NOT NULL,
    especialidade      VARCHAR2(100)  NOT NULL,
    registro_conselho  VARCHAR2(30)   NOT NULL,
    criado_em          TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_profissional_registro UNIQUE (registro_conselho)
);

CREATE TABLE agendamento (
    id                    NUMBER(19,0)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id           NUMBER(19,0)   NOT NULL,
    profissional_id       NUMBER(19,0)   NOT NULL,
    data_hora             TIMESTAMP      NOT NULL,
    tipo_atendimento      VARCHAR2(30)   NOT NULL,
    status                VARCHAR2(20)   NOT NULL,
    motivo_cancelamento   VARCHAR2(500),
    cancelado_em          TIMESTAMP,
    criado_em             TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_agendamento_paciente     FOREIGN KEY (paciente_id)     REFERENCES paciente(id),
    CONSTRAINT fk_agendamento_profissional FOREIGN KEY (profissional_id) REFERENCES profissional(id),
    CONSTRAINT ck_agendamento_status       CHECK (status IN ('AGENDADO','CANCELADO','REALIZADO')),
    CONSTRAINT ck_agendamento_tipo         CHECK (tipo_atendimento IN ('CONSULTA','RETORNO','EXAME'))
);

CREATE INDEX ix_agendamento_paciente     ON agendamento (paciente_id);
CREATE INDEX ix_agendamento_profissional ON agendamento (profissional_id);
CREATE INDEX ix_agendamento_status       ON agendamento (status);
