-- Schema H2: usa BIGINT (compativel com Long do JPA via H2Dialect).
CREATE TABLE paciente (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(150)    NOT NULL,
    cpf             VARCHAR(14)     NOT NULL,
    email           VARCHAR(150),
    telefone        VARCHAR(20),
    data_nascimento DATE,
    criado_em       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_paciente_cpf UNIQUE (cpf)
);

CREATE TABLE profissional (
    id                 BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(150)   NOT NULL,
    especialidade      VARCHAR(100)   NOT NULL,
    registro_conselho  VARCHAR(30)    NOT NULL,
    criado_em          TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_profissional_registro UNIQUE (registro_conselho)
);

CREATE TABLE agendamento (
    id                    BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id           BIGINT         NOT NULL,
    profissional_id       BIGINT         NOT NULL,
    data_hora             TIMESTAMP      NOT NULL,
    tipo_atendimento      VARCHAR(30)    NOT NULL,
    status                VARCHAR(20)    NOT NULL,
    motivo_cancelamento   VARCHAR(500),
    cancelado_em          TIMESTAMP,
    criado_em             TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_agendamento_paciente     FOREIGN KEY (paciente_id)     REFERENCES paciente(id),
    CONSTRAINT fk_agendamento_profissional FOREIGN KEY (profissional_id) REFERENCES profissional(id),
    CONSTRAINT ck_agendamento_status       CHECK (status IN ('AGENDADO','CANCELADO','REALIZADO')),
    CONSTRAINT ck_agendamento_tipo         CHECK (tipo_atendimento IN ('CONSULTA','RETORNO','EXAME'))
);

CREATE INDEX ix_agendamento_paciente     ON agendamento (paciente_id);
CREATE INDEX ix_agendamento_profissional ON agendamento (profissional_id);
CREATE INDEX ix_agendamento_status       ON agendamento (status);
